import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { adminCreate, adminListAll, adminUpdate } from "@/lib/touba-infos-store";
export const dynamic="force-dynamic";
const D="2026-09-06T08:00:00.000Z";
const S=(n:string,u:string)=>`<h2>Sources</h2><p><strong>Source :</strong> <a href="${u}" target="_blank" rel="noopener noreferrer">${n}</a>.</p>`;
const A=[
["Touba","TOUBA : LE SET SETAL DES BAYE FALL PROLONGE LE KHIDMA APRÈS LE GRAND MAGAL","La mobilisation pour nettoyer la ville sainte se poursuit après le Grand Magal.","À Touba, l’après-Magal se joue aussi dans la propreté et la mobilisation citoyenne.","<p>Les Baye Fall ont lancé une vaste opération de Set Setal à Touba après le Grand Magal, avec un appel à une mobilisation large des disciples de Serigne Touba et des musulmans.</p><p>Cette initiative rappelle que l’organisation d’un rassemblement de cette ampleur ne s’arrête pas au départ des pèlerins. La remise en état des espaces publics, l’évacuation des déchets et la préservation du cadre de vie font pleinement partie du service à la cité.</p>","APS","https://aps.sn/touba-les-baye-fall-lancent-une-operation-de-set-setal-apres-le-magal/"],
["Sénégal","ENGAGEMENT CITOYEN : LE PRÉSIDENT APPELLE À UNE MOBILISATION DURABLE POUR LE CADRE DE VIE","Bassirou Diomaye Faye a participé au lancement du programme national d’engagement citoyen.","Le chef de l’État veut inscrire le nettoyage, la végétalisation et l’embellissement dans la durée.","<p>Le président Bassirou Diomaye Faye a pris part le 5 septembre au lancement du Programme national d’engagement citoyen autour du stade Léopold Sédar Senghor. L’opération combine nettoiement, végétalisation et embellissement.</p><p>Cette mobilisation s’inscrit dans les préparatifs des JOJ Dakar 2026, mais le message présidentiel dépasse l’événement sportif : l’amélioration du cadre de vie doit devenir une responsabilité durable des citoyens et des collectivités.</p>","RTS / Présidence","https://www.rts.sn/actualite/detail/a-la-une/set-te-yanji-le-president-faye-appelle-a-une-mobilisation-citoyenne-durable"],
["Politique","VIE CHÈRE : LA PRESSION SOCIALE REMET LE POUVOIR D’ACHAT AU CENTRE DU DÉBAT PUBLIC","Une marche contre la cherté de la vie s’est tenue samedi à Dakar.","Le pouvoir d’achat revient au premier plan des attentes adressées aux pouvoirs publics.","<p>Plusieurs dizaines de personnes ont marché samedi à Dakar à l’appel du collectif « 30 Jours pour le Juste Prix » pour dénoncer la cherté de la vie et la baisse du pouvoir d’achat.</p><p>Au-delà de la mobilisation, cet épisode remet au centre du débat politique les prix, les loyers et les dépenses quotidiennes des ménages. La réponse publique sera jugée sur les effets concrets des mesures annoncées.</p>","APS","https://aps.sn/contre-la-vie-chere-des-senegalais-marchent-dans-les-rues-de-dakar/"],
["Société","VIE CHÈRE : DES CITOYENS MARCHENT À DAKAR POUR RÉCLAMER DES PRIX PLUS JUSTES","Le collectif 30 Jours pour le Juste Prix a organisé une marche à Dakar.","Les difficultés quotidiennes des ménages s’expriment désormais aussi dans la rue.","<p>Une marche contre la cherté de la vie a réuni samedi plusieurs dizaines de personnes à Dakar. Les participants ont notamment dénoncé le niveau des prix, des loyers et des dépenses d’électricité.</p><p>La mobilisation montre que la question du coût de la vie reste une préoccupation sociale forte. Elle appelle à suivre les mesures publiques sur les prix et leur impact réel sur le budget des familles.</p>","APS","https://aps.sn/contre-la-vie-chere-des-senegalais-marchent-dans-les-rues-de-dakar/"],
["Économie","SÉNÉGAL–FMI : L’ACCORD TECHNIQUE DE 2,2 MILLIARDS DE DOLLARS ENTRE DANS UNE PHASE DÉCISIVE","Le programme envisagé sur 36 mois doit encore franchir les étapes d’approbation du FMI.","L’enjeu est désormais de transformer l’accord technique en programme effectif et en résultats économiques.","<p>Le Sénégal et les services du FMI sont parvenus à un accord au niveau des services sur un programme de 36 mois d’environ 2,2 milliards de dollars.</p><p>Cette étape reste soumise à l’approbation de la direction et du Conseil d’administration du Fonds. Le futur programme doit accompagner le redressement des finances publiques, la gestion de la dette et la relance économique.</p>","RTS / FMI","https://www.rts.sn/actualite/detail/a-la-une/senegal-fmi-un-accord-de-principe-sur-un-programme-de-financement-de-22-milliards-de-dollars-sur-36-mois"],
["Religion","DEUX RAKKAS : SAINT-LOUIS PERPÉTUE LA MÉMOIRE DE CHEIKH AHMADOU BAMBA","La prière historique du 5 septembre 1895 a été commémorée en présence de nombreux fidèles.","La communauté mouride a renouvelé à Saint-Louis l’un des grands symboles de son histoire spirituelle.","<p>La traditionnelle prière des deux rakkas effectuée par Cheikh Ahmadou Bamba le 5 septembre 1895 a été commémorée samedi à Saint-Louis, en présence de Serigne Mame Mor Mbacké, d’autorités et de nombreux fidèles.</p><p>La cérémonie perpétue un épisode considéré dans la mémoire mouride comme un acte de foi, de dignité et de résistance spirituelle face au pouvoir colonial.</p>","APS","https://aps.sn/saint-louis-la-priere-des-deux-rakkas-perpetuee-par-la-communaute-mouride/"],
["Magal","MAGAL DES DEUX RAKKAS : SAINT-LOUIS RENOUVELLE UN RENDEZ-VOUS MAJEUR DE LA MÉMOIRE MOURIDE","La Gouvernance de Saint-Louis a accueilli la commémoration du geste historique de Serigne Touba.","Le 5 septembre reste une date centrale dans la transmission de l’histoire mouride.","<p>De nombreux fidèles se sont retrouvés à Saint-Louis pour le Magal des deux Rakkas. L’ancien Palais du gouverneur de l’AOF demeure le lieu symbolique de cette commémoration.</p><p>Le rendez-vous rappelle la prière accomplie par Cheikh Ahmadou Bamba le 5 septembre 1895, avant son exil au Gabon, et transmet aux nouvelles générations une séquence fondamentale de l’histoire mouride.</p>","APS","https://aps.sn/saint-louis-lancien-palais-du-gouverneur-de-laof-haut-lieu-de-la-commemoration-du-magal-des-deux-rakkas/"],
["Afrique","LIGUE DES CHAMPIONS CAF : TEUNGUETH FC S’IMPOSE À BISSAU ET PREND UNE OPTION","Le champion du Sénégal a battu FC Cantchungo 1-0 à l’extérieur.","Un but tardif de Mame Birame Diaw place TFC en bonne position avant le retour à Dakar.","<p>Teungueth FC a remporté samedi à Bissau la manche aller du premier tour de la Ligue des champions africaine face au Futebol Clube de Cantchungo sur le score de 1-0.</p><p>Mame Birame Diaw a inscrit l’unique but à la 89e minute. Le champion du Sénégal dispose ainsi d’un avantage avant le match retour prévu à Dakar.</p>","APS","https://aps.sn/ligue-des-champions-tfc-bat-son-adversaire-bissau-guineen-1-0-et-prend-une-option-pour-le-second-tour/"],
["International","MIGRATION : LE RETOUR VOLONTAIRE DE SÉNÉGALAIS DEPUIS LE MAROC RESTE UN DÉFI D’ACCOMPAGNEMENT","Un premier convoi de 120 Sénégalais a été annoncé dans le cadre des rapatriements volontaires.","Au-delà du transport, la réinsertion des migrants revenus au pays constitue l’étape suivante.","<p>Les autorités consulaires ont organisé le retour volontaire d’un premier groupe de 120 Sénégalais depuis le Maroc, par voie terrestre via la Mauritanie.</p><p>Cette opération concerne des migrants secourus ou interceptés en mer. Elle remet également en lumière les besoins d’accueil, d’orientation et de réinsertion économique après le retour.</p>","APS / RTS","https://aps.sn/un-premier-groupe-de-120-migrants-senegalais-va-etre-rapatrie-du-maroc-vendredi-source-diplomatique/"],
["Sport","JOJ DAKAR 2026 : LE PRÉSIDENT VEUT FAIRE DES INFRASTRUCTURES UN HÉRITAGE DURABLE","Bassirou Diomaye Faye appelle à faire vivre les équipements avant, pendant et après les Jeux.","L’enjeu des JOJ dépasse désormais la compétition sportive et concerne l’emploi et la vie des quartiers.","<p>Lors du lancement de Dundal JOJ, le président Bassirou Diomaye Faye a appelé à faire des infrastructures réalisées pour les Jeux olympiques de la jeunesse des pôles durables d’activités et d’emplois.</p><p>Le Sénégal accueillera les JOJ du 31 octobre au 13 novembre 2026. Pour le chef de l’État, leur héritage devra continuer à bénéficier aux populations bien après la compétition.</p>","APS","https://aps.sn/le-president-de-la-republique-appelle-a-faire-des-infrastructures-des-poles-dactivites-et-demplois-au-dela-des-joj/"],
["Culture","CULTURES URBAINES : 570 MILLIONS FCFA POUR SOUTENIR 244 PROJETS","Le fonds dédié aux cultures urbaines et industries créatives finance des projets issus des 14 régions.","L’objectif est d’aider les créateurs à transformer leur activité artistique en métier durable.","<p>Le Fonds de développement des cultures urbaines et des industries créatives a mobilisé 570 millions de francs CFA pour 244 projets artistiques et actions de mobilité.</p><p>Sur 1 368 dossiers enregistrés, 855 dossiers complets issus des 14 régions ont été examinés. Les bénéficiaires doivent contractualiser les activités, le calendrier et les modalités de financement.</p>","APS / FDCUIC","https://aps.sn/une-enveloppe-de-570-millions-fcfa-mobilisee-pour-244-projets-culturels/"],
["Environnement","CADRE DE VIE : PLUS DE 200 AGENTS MOBILISÉS AUTOUR DU STADE LÉOPOLD SÉDAR SENGHOR","Les opérations de désencombrement, d’embellissement et de végétalisation ont été officiellement lancées.","Les préparatifs des JOJ deviennent aussi un chantier de transformation du cadre de vie.","<p>Plus de 200 agents du programme Xëyu Ndaw Yi ont été mobilisés autour du stade Léopold Sédar Senghor pour des opérations de désencombrement, d’aménagement et de végétalisation.</p><p>La Direction générale du Cadre de vie indique que la dynamique doit également être étendue à plusieurs quartiers de Dakar et à d’autres localités du pays.</p>","APS / Direction générale du Cadre de vie","https://aps.sn/les-operations-dembellissement-des-abords-du-stade-lss-officiellement-lancees/"],
["Santé","DIPHTÉRIE : 34 CAS CONFIRMÉS ET SIX DÉCÈS, LA RIPOSTE SANITAIRE SE RENFORCE","Huit districts sanitaires de six régions sont concernés depuis le premier cas confirmé le 1er août.","Kédougou concentre l’essentiel des cas signalés par le ministère de la Santé.","<p>Le Sénégal a enregistré 34 cas confirmés de diphtérie, dont six décès, selon le ministère de la Santé et de l’Hygiène publique. Les cas concernent huit districts sanitaires répartis dans six régions.</p><p>Le ministère a renforcé la prise en charge, les investigations autour des cas et l’identification des contacts. L’information officielle et la vaccination restent centrales dans la riposte.</p>","RTS / Ministère de la Santé","https://www.rts.sn/actualite/detail/sante/diphterie-au-senegal-34-cas-confirmes-et-six-deces-depuis-le-1er-aout"],
["Éducation","ÉDUCATION INCLUSIVE : LE SÉNÉGAL VEUT UNE ÉCOLE ACCESSIBLE À TOUS LES ENFANTS","Le handicap est placé au cœur de la refondation du système éducatif.","Le futur Forum national doit renforcer la prise en charge des élèves ayant des besoins éducatifs particuliers.","<p>Le ministère de l’Éducation nationale veut faire de l’éducation inclusive un axe de la refondation de l’école sénégalaise. Un atelier préparatoire au Forum national sur l’éducation inclusive s’est tenu les 3 et 4 septembre à Dakar.</p><p>L’objectif est d’améliorer l’accès à l’école et l’accompagnement des enfants en situation de handicap ou ayant des besoins éducatifs particuliers.</p>","APS / Ministère de l’Éducation","https://aps.sn/education-inclusive-le-senegal-consolide-sa-politique-pour-une-ecole-accessible-a-tous/"],
["Diaspora","DIASPORA : APRÈS LE RAPATRIEMENT DU MAROC, LE DÉFI DE LA RÉINSERTION","Le retour volontaire de migrants sénégalais pose la question de leur accompagnement une fois au pays.","L’action consulaire doit se prolonger par des solutions concrètes de réinsertion.","<p>Un premier groupe de 120 Sénégalais a été annoncé au départ du Maroc dans le cadre d’un rapatriement volontaire. D’autres compatriotes restent dans des centres d’accueil au sud du Maroc.</p><p>Au-delà du retour physique, l’enjeu est désormais celui de l’accueil, de l’accompagnement psychosocial, de la formation et de la réinsertion économique des personnes revenues.</p>","APS / RTS","https://www.rts.sn/actualite/detail/a-la-une/maroc-120-senegalais-attendus-au-pays-dans-le-cadre-dun-rapatriement-volontaire"],
["Technologies","NUMÉRIQUE : LA CONNECTIVITÉ DES TERRITOIRES RESTE UN CHANTIER STRATÉGIQUE POUR LE SÉNÉGAL","Le programme de connectivité universelle vise à réduire la fracture numérique dans les zones éloignées.","Écoles, centres de santé et communautés vulnérables figurent parmi les cibles prioritaires.","<p>Le Sénégal poursuit son programme national de connectivité universelle, qui s’appuie notamment sur le déploiement de solutions satellitaires dans les zones insuffisamment couvertes.</p><p>L’objectif annoncé par les autorités est de rapprocher les services numériques des populations, avec une priorité accordée aux écoles, aux structures de santé et aux communautés vulnérables. L’enjeu reste de transformer la connectivité en accès effectif aux services et aux opportunités.</p>","RTS / Ministère du Numérique","https://www.rts.sn/actualite/detail/a-la-une/connectivite-universelle-lancement-de-la-tournee-de-deploiement-des-kits-satellitaires"]
] as const;
export async function GET(){
 const all=await adminListAll(); for(const x of all) if(x.alaUne) await adminUpdate(x.id,{alaUne:false});
 const made=[];
 for(const [categorie,titre,sousTitre,extrait,body,source,url] of A){
  const exists=(await adminListAll()).find(x=>x.titre===titre);
  if(exists){if(categorie==="Touba"&&!exists.alaUne)await adminUpdate(exists.id,{alaUne:true,epingle:true});made.push(exists);continue;}
  const a=await adminCreate({titre,sousTitre,extrait,categorie,genre:categorie==="Politique"||categorie==="Économie"||categorie==="Diaspora"||categorie==="Technologies"?"Analyse":"Actualité",statut:"publie",auteur:"Rédaction Touba Infos",date:D,tempsLecture:"3 min",imageEmoji:"📰",imageGradient:"from-emerald-950 via-green-800 to-green-900",credit:`Source éditoriale : ${source}`,legende:titre,alaUne:categorie==="Touba",breaking:false,epingle:categorie==="Touba",vues:0,tags:[categorie,"6 septembre 2026"],contenu:body+S(source,url)}); made.push(a);
 }
 revalidatePath("/touba-infos"); revalidatePath("/touba-infos/fil-info"); revalidatePath("/");
 return NextResponse.json({ok:true,count:made.length,une:made.find(x=>x.alaUne)?.slug,articles:made.map(x=>({id:x.id,slug:x.slug,categorie:x.categorie}))});
}
