import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { adminCreate, adminListAll, adminUpdate } from "@/lib/touba-infos-store";

export const dynamic = "force-dynamic";
const D="2026-09-03T08:15:00.000Z";
const S=(name:string,url:string)=>`<h2>Sources</h2><p><strong>Source :</strong> <a href="${url}" target="_blank" rel="noopener noreferrer">${name}</a>.</p>`;
const A=[
["Touba","TOUBA : LES BAYE FALL LANCENT UN GRAND « SET SETAL » APRÈS LE MAGAL","Au lendemain du Grand Magal, les Baye Fall appellent à une mobilisation large pour nettoyer la ville sainte.","L’opération de salubrité lancée à Touba place l’après-Magal au cœur de la responsabilité collective.","<p>Les Baye Fall ont lancé mercredi 2 septembre une opération de nettoiement à Touba. L’appel, relayé par l’Agence de presse sénégalaise, invite les disciples mourides et plus largement les musulmans à participer à la remise en état de la ville après le Grand Magal.</p><h2>Une mobilisation qui dépasse les Baye Fall</h2><p>Serigne Fallou Fall a insisté sur le caractère collectif de l’initiative. L’enjeu est concret : après un rassemblement de l’ampleur du Magal, la propreté, l’évacuation des déchets et le retour rapide à un cadre de vie normal deviennent une priorité urbaine.</p><p>Pour Touba, cette opération rappelle que la réussite du Magal se mesure aussi dans l’après-événement. La mobilisation citoyenne peut compléter les dispositifs publics et contribuer à installer une culture durable de la propreté.</p>","APS","https://aps.sn/touba-les-baye-fall-lancent-une-operation-de-nettoiement-apres-le-magal/"],
["Sénégal","CONSEIL DES MINISTRES : LES PRIORITÉS ÉCONOMIQUES ET SOCIALES REMISES AU CENTRE","Le Conseil des ministres du 2 septembre a fixé plusieurs orientations sur l’investissement, les hydrocarbures, la formation et l’action publique.","Le gouvernement ouvre la rentrée de septembre avec un agenda chargé sur l’économie et les politiques publiques.","<p>Le Conseil des ministres du mercredi 2 septembre 2026, présidé par le chef de l’État Bassirou Diomaye Faye, a abordé plusieurs dossiers structurants. La Présidence et la RTS mettent notamment en avant de nouvelles orientations concernant l’investissement, les hydrocarbures et la formation.</p><h2>Une rentrée sous pression</h2><p>Cette séquence intervient alors que les urgences économiques et sociales occupent une place importante dans le débat public. L’exécution des décisions et leur traduction concrète dans les services publics seront donc particulièrement suivies.</p>","Présidence du Sénégal","https://www.presidence.sn/fr/actualites/communique-du-conseil-des-ministres-du-mercredi-2-septembre-2026"],
["Politique","DPG : LE PREMIER MINISTRE ATTENDU À L’ASSEMBLÉE NATIONALE LE 8 SEPTEMBRE","La Conférence des présidents a fixé au 8 septembre la séance consacrée à la Déclaration de politique générale.","Le rendez-vous parlementaire du 8 septembre sera un moment politique majeur de la rentrée.","<p>La Déclaration de politique générale du Premier ministre est programmée au mardi 8 septembre 2026 à l’Assemblée nationale, selon la RTS. Cette séance doit permettre au chef du gouvernement de présenter les priorités et la méthode de l’exécutif devant les députés.</p><p>Dans un contexte marqué par l’accord technique avec le FMI, la dette et les attentes sociales, les orientations économiques devraient occuper une place centrale dans les échanges.</p>","RTS","https://www.rts.sn/actualite/detail/a-la-une/assemblee-nationale-la-dpg-du-premier-ministre-programmee-le-8-septembre"],
["Société","EMPLOI : L’EMPLOYABILITÉ DES DIPLÔMÉS EN LANGUES AU CŒUR DES PRÉOCCUPATIONS","Un appel à mieux connecter les compétences universitaires aux besoins du marché du travail a été relayé dans l’actualité régionale.","La question de l’insertion des diplômés revient au premier plan.","<p>L’employabilité des diplômés, notamment ceux issus des filières de langues, fait partie des sujets sociaux mis en avant cette semaine. Le défi dépasse la formation : il concerne l’adéquation entre compétences, besoins des entreprises et accompagnement vers l’emploi.</p><p>Pour les jeunes Sénégalais, l’enjeu est de transformer les acquis universitaires en compétences directement valorisables dans les secteurs du tourisme, du numérique, de la traduction, du commerce et des services.</p>","APS","https://aps.sn/category/regions/"],
["Économie","SÉNÉGAL–FMI : CE QUE CHANGE RÉELLEMENT LE PROGRAMME DE 1 243 MILLIARDS FCFA","L’accord technique porte sur environ 2,2 milliards de dollars sur 36 mois, mais reste soumis à l’approbation du Conseil d’administration du FMI.","Le financement doit soutenir le redressement des finances publiques et accompagner le traitement de la dette.","<p>Le Sénégal et les services du FMI ont conclu le 1er septembre un accord au niveau des services autour d’une Facilité élargie de crédit d’environ 2,2 milliards de dollars, soit près de 1 243 milliards FCFA, sur 36 mois.</p><p>Le FMI précise toutefois que l’accord reste soumis à l’approbation de sa direction et de son Conseil d’administration. Le programme vise notamment le renforcement des finances publiques, la transparence budgétaire et l’amélioration de l’environnement des affaires.</p><h2>La dette au cœur du dossier</h2><p>En parallèle, le gouvernement a lancé un Plan de traitement de la dette afin de réduire la pression du service de la dette sur les finances publiques.</p>","FMI","https://www.imf.org/fr/news/articles/2026/09/01/pr26282-senegal-imf-reaches-sla-ecf-arrangement"],
["Religion","TOUBA : 20 DAARAS REÇOIVENT DES KITS ALIMENTAIRES","Vingt écoles coraniques de Touba ont bénéficié d’un appui alimentaire dans le cadre d’un projet d’assistance nutritionnelle.","Un soutien ciblé aux daaras de la ville sainte.","<p>Vingt daaras basés à Touba ont reçu mardi des kits alimentaires à Darou Tanzil. L’opération s’inscrit dans un projet d’assistance alimentaire et nutritionnelle porté par le Conseil national de développement de la nutrition, avec l’appui de la Société africaine de raffinage.</p><p>Au-delà de l’aide ponctuelle, cette initiative remet en lumière les besoins structurels des daaras en matière d’alimentation, de santé et d’accompagnement des apprenants.</p>","APS","https://aps.sn/des-kits-alimentaires-distribues-a-20-daaras-bases-a-touba/"],
["Magal","APRÈS LE MAGAL 2026 : LE KHIDMA SE PROLONGE DANS LA PROPRETÉ DE TOUBA","Le service communautaire ne s’arrête pas avec le départ des pèlerins : l’opération Set Setal prolonge la mobilisation.","L’après-Magal devient un temps de service et de remise en état de la cité.","<p>Le Grand Magal du 2 août est passé, mais la logique du khidma se poursuit. L’appel des Baye Fall au nettoiement de Touba donne une dimension très concrète au service après l’événement.</p><p>Cette phase est essentielle : un grand rassemblement produit des volumes importants de déchets et sollicite fortement les réseaux urbains. Faire de l’après-Magal une séquence organisée à part entière permettrait d’améliorer durablement l’image et le fonctionnement de la ville.</p>","APS","https://aps.sn/touba-les-baye-fall-lancent-une-operation-de-nettoiement-apres-le-magal/"],
["Afrique","GASTRONOMIE : TROIS CHEFS SÉNÉGALAIS EN ROUTE POUR LE BOCUSE D’OR AFRICA","Le Sénégal sera représenté à Agadir du 22 au 24 septembre par une équipe de trois professionnels.","La gastronomie sénégalaise vise une qualification pour la finale mondiale.","<p>Trois chefs représenteront le Sénégal à la phase africaine du Bocuse d’Or prévue du 22 au 24 septembre à Agadir, au Maroc. L’équipe comprend deux chefs en pâtisserie et un en gastronomie, selon la Fédération nationale des cuisiniers du Sénégal.</p><p>Au-delà de la compétition, cette présence constitue une vitrine pour les savoir-faire culinaires sénégalais et leur potentiel dans l’économie culturelle et touristique africaine.</p>","APS","https://aps.sn/le-senegal-represente-par-trois-chefs-au-bocuse-dor-africa-2026/"],
["International","FMI–SÉNÉGAL : UN ACCORD TECHNIQUE QUI DOIT ENCORE FRANCHIR L’ÉTAPE DU CONSEIL D’ADMINISTRATION","Le FMI confirme un accord au niveau des services pour un programme de 36 mois.","L’annonce est importante, mais elle ne constitue pas encore l’approbation définitive du financement.","<p>Le Fonds monétaire international a annoncé le 1er septembre un accord au niveau des services avec le Sénégal pour un programme de 36 mois au titre de la Facilité élargie de crédit.</p><p>Le Fonds souligne que l’accord reste soumis à l’approbation de sa direction et de son Conseil d’administration. Cette précision est importante : les conditions définitives et le calendrier des décaissements seront mieux connus après cette étape.</p>","FMI","https://www.imf.org/en/news/articles/2026/09/01/pr26282-senegal-imf-reaches-sla-ecf-arrangement"],
["Sport","LIGUE DES CHAMPIONS CAF : TEUNGUETH FC VEUT RETROUVER LES SOMMETS AFRICAINS","Le champion du Sénégal prépare son entrée en Ligue africaine des champions avec l’ambition de rééditer son parcours de 2020-2021.","Teungueth FC porte les espoirs sénégalais sur la scène continentale.","<p>Champion du Sénégal, Teungueth FC s’apprête à lancer une nouvelle campagne en Ligue africaine des champions. Le club de Rufisque affiche l’ambition de retrouver le niveau atteint lors de la saison 2020-2021.</p><p>Cette campagne arrive à quelques semaines de la reprise de la Ligue 1 sénégalaise, annoncée pour le 3 octobre. La préparation sportive et la gestion de l’effectif seront déterminantes.</p>","APS","https://aps.sn/ligue-des-champions-teungueth-fc-veut-reediter-son-exploit-de-la-saison-2020-2021/"],
["Culture","SAINT-LOUIS : UNE RENTRÉE CULTURELLE ENTRE PATRIMOINE, MUSIQUE ET CRÉATION","La programmation de septembre-octobre met en avant littérature, musique, patrimoine gastronomique et jeunesse.","Saint-Louis ouvre une séquence culturelle riche pour les prochaines semaines.","<p>L’Institut français de Saint-Louis a dévoilé une programmation de septembre et octobre articulée autour du patrimoine, de la création contemporaine et du sport. Des rendez-vous littéraires et musicaux sont annoncés, ainsi qu’une mise en valeur du patrimoine gastronomique.</p><p>Cette programmation confirme le rôle de Saint-Louis comme l’un des pôles culturels majeurs du Sénégal.</p>","APS","https://aps.sn/saint-louis-linstitut-francais-devoile-son-agenda-culturel-pour-septembre-et-octobre-2/"],
["Environnement","MÉTÉO : PLUIES ET ORAGES ATTENDUS SUR UNE GRANDE PARTIE DU SÉNÉGAL","L’ANACIM prévoit des activités pluvio-orageuses sur le Sud, le Centre et possiblement le littoral.","La vigilance reste de mise face aux pluies annoncées jusqu’à jeudi.","<p>L’ANACIM annonce des pluies et des orages sur une grande partie du Sud et du Centre du Sénégal, notamment à Kédougou, Kolda, Sédhiou, Ziguinchor, Tambacounda, Kaffrine, Kaolack, Diourbel et Fatick.</p><p>Les activités pourraient ensuite s’étendre vers le littoral, notamment Saint-Louis, Louga et Dakar. Dans les zones sensibles aux inondations, ces prévisions appellent à une attention particulière sur l’évacuation des eaux.</p>","APS / ANACIM","https://aps.sn/pluies-et-orages-attendus-sur-une-grande-partie-du-pays/"],
["Santé","COUVERTURE MALADIE : LE SÉNÉGAL VEUT ALLER VERS UN SYSTÈME NATIONAL INTÉGRÉ","Les autorités poursuivent la réforme de la protection sociale en santé avec l’objectif d’améliorer l’accès aux soins.","La couverture universelle du risque maladie revient au centre de l’agenda sanitaire.","<p>Le Sénégal poursuit sa réforme de la protection sociale en santé avec l’ambition de garantir un meilleur accès aux soins. Les autorités travaillent à la mise en place d’un système national intégré de couverture universelle du risque maladie.</p><p>Le principal défi sera de transformer l’ambition institutionnelle en couverture effective : adhésion, financement, prise en charge des soins et accès dans les territoires.</p>","APS","https://aps.sn/couverture-maladie-le-senegal-veut-garantir-lacces-aux-soins-pour-tous/"],
["Éducation","UNIVERSITÉ DE MATAM : COURSE CONTRE LA MONTRE AVANT L’OUVERTURE PRÉVUE EN OCTOBRE","Le recteur appelle à accélérer les travaux pour permettre l’ouverture de l’établissement dans les délais.","Le chantier universitaire de Matam entre dans une phase décisive.","<p>Le recteur de l’Université Souleymane Niang de Matam a appelé à accélérer les travaux en vue d’une ouverture annoncée en octobre. L’enjeu est important pour l’accès à l’enseignement supérieur dans le nord du pays.</p><p>La réussite du démarrage dépendra à la fois de l’achèvement des infrastructures, de l’équipement, du recrutement et des conditions d’accueil des premiers étudiants.</p>","APS","https://aps.sn/universite-de-matam-le-recteur-appelle-a-accelerer-les-travaux-pour-une-ouverture-en-octobre-prochain/"],
["Diaspora","DIASPORA : POURQUOI L’ÉPARGNE DES SÉNÉGALAIS DE L’EXTÉRIEUR RESTE STRATÉGIQUE","Dans un contexte de besoins élevés de financement, la mobilisation de l’épargne de la diaspora revient au cœur du débat économique.","Les Diaspora Bonds peuvent devenir un outil complémentaire, à condition d’offrir transparence et confiance.","<p>La question de la mobilisation de l’épargne des Sénégalais de l’extérieur prend une nouvelle importance avec les besoins de financement du pays et la stratégie de gestion de la dette.</p><p>L’idée des « Diaspora Bonds » consiste à proposer aux Sénégalais établis à l’étranger des instruments d’investissement dédiés au financement national. Leur succès dépend toutefois de conditions claires : transparence sur l’utilisation des fonds, rendement lisible, sécurité juridique et suivi des projets financés.</p>","APS","https://aps.sn/diaspora-bonds-un-grand-bond-vers-la-souverainete-economique/"],
["Technologies","NUMÉRIQUE : L’INCLUSION LOCALE, UN ENJEU DE SERVICES PUBLICS ET D’EMPLOI","La transformation numérique ne peut réussir sans accompagnement des collectivités et des publics éloignés des outils digitaux.","Le Sénégal doit faire de l’inclusion numérique un volet concret de la modernisation publique.","<p>À mesure que les démarches administratives, paiements et services se numérisent, l’inclusion numérique devient un enjeu de politique publique. Les initiatives de volontariat numérique expérimentées au Sénégal montrent l’intérêt d’un accompagnement de proximité.</p><p>Pour les collectivités, la priorité est double : faciliter l’accès des citoyens aux services digitaux et développer des compétences locales capables de soutenir cette transition.</p>","APS","https://aps.sn/gouvernance-locale-lancement-officiel-du-projet-de-volontariat-pour-linclusion-numerique/"],
] as const;

export async function GET(){
 const all=await adminListAll();
 for(const x of all) if(x.alaUne) await adminUpdate(x.id,{alaUne:false});
 const made=[];
 for(const [categorie,titre,sousTitre,extrait,body,source,url] of A){
  const exists=(await adminListAll()).find(x=>x.titre===titre);
  if(exists){made.push(exists);continue;}
  const a=await adminCreate({titre,sousTitre,extrait,categorie,genre:categorie==="Diaspora"||categorie==="Technologies"?"Analyse":"Actualité",statut:"publie",auteur:"Rédaction Touba Infos",date:D,tempsLecture:"3 min",imageEmoji:"📰",imageGradient:"from-green-700 via-emerald-800 to-green-900",credit:`Source éditoriale : ${source}`,legende:titre,alaUne:categorie==="Touba",breaking:false,epingle:categorie==="Touba",vues:0,tags:[categorie,"3 septembre 2026"],contenu:body+S(source,url)}); made.push(a);
 }
 revalidatePath("/touba-infos","layout"); revalidatePath("/","layout");
 return NextResponse.json({ok:true,count:made.length,une:made.find(x=>x.alaUne)?.slug,articles:made.map(x=>({id:x.id,slug:x.slug,categorie:x.categorie}))});
}