import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { adminCreate, adminListAll, adminUpdate } from "@/lib/touba-infos-store";
export const dynamic="force-dynamic";
const D="2026-09-05T08:00:00.000Z";
const S=(n:string,u:string)=>`<h2>Sources</h2><p><strong>Source :</strong> <a href="${u}" target="_blank" rel="noopener noreferrer">${n}</a>.</p>`;
const A=[
["Touba","5 SEPTEMBRE 1895 : LE JOUR OÙ SERIGNE TOUBA AFFIRMA SA LIBERTÉ SPIRITUELLE À SAINT-LOUIS","Le 5 septembre rappelle l’épisode des deux rakkas accomplies par Cheikh Ahmadou Bamba avant sa déportation au Gabon.","Une date majeure de la mémoire mouride, relue à la lumière du parcours de résistance spirituelle de Serigne Touba.","<p>Le 5 septembre 1895 occupe une place particulière dans la mémoire mouride. Ce jour-là à Saint-Louis, Cheikh Ahmadou Bamba fut jugé par l’administration coloniale avant sa déportation au Gabon. L’APS rappelle qu’il accomplit deux rakkas dans le bureau du gouverneur de l’Afrique occidentale française.</p><h2>Une mémoire toujours vivante</h2><p>Le Magal des deux rakkas perpétue cet acte de foi et de dignité. Plus de cent trente ans après, cette séquence reste un repère pour comprendre le message de résistance pacifique, de savoir et de spiritualité porté par le fondateur du mouridisme.</p>","APS","https://aps.sn/serigne-touba-le-long-chemin-de-la-liberte-et-de-la-resilience/"],
["Sénégal","ÉTAT–PATRONAT : LE DIALOGUE SUR L’EMPLOI ET L’ÉCONOMIE SE RENFORCE","Le président Bassirou Diomaye Faye a reçu une délégation du Conseil national du Patronat conduite par Baïdy Agne.","Le secteur privé a remis un mémorandum au chef de l’État, qui veut installer une concertation régulière.","<p>Le chef de l’État a reçu le 3 septembre une délégation du Conseil national du Patronat du Sénégal. Selon la RTS, citant la Présidence, les échanges ont porté sur les préoccupations des employeurs et sur les moyens de renforcer la coopération entre l’État et le secteur privé.</p><p>Le patronat a remis un mémorandum au Président. Pour les entreprises comme pour les travailleurs, l’enjeu sera désormais de mesurer les effets concrets de ce dialogue sur l’investissement et l’emploi.</p>","RTS / Présidence","https://www.rts.sn/actualite/detail/a-la-une/etat-patronat-chef-de-letat-reaffirme-sa-volonte-de-renforcer-la-concertation"],
["Politique","APRÈS LA DPG, LE GOUVERNEMENT FACE AU TEST DE L’EXÉCUTION","La Déclaration de politique générale du Premier ministre ouvre désormais une phase de suivi des engagements publics.","Au-delà du débat parlementaire, la question centrale devient celle du calendrier et des résultats.","<p>Le Premier ministre Ahmadou Al Aminou Lo a présenté sa Déclaration de politique générale le 1er septembre devant l’Assemblée nationale. Cette étape républicaine a exposé les grandes orientations de l’action gouvernementale dans le cadre de l’Agenda Sénégal 2050.</p><h2>Le temps du suivi</h2><p>Pour les citoyens, l’enjeu se déplace maintenant vers l’exécution : emploi, services publics, finances, investissements et transformation des territoires devront pouvoir être suivis à travers des résultats mesurables.</p>","RTS / Primature","https://www.rts.sn/actualite/detail/a-la-une/declaration-de-politique-generale-ahmadou-al-aminou-lo-attendu-a-lassemblee-nationale-le-1er-septembre"],
["Société","ALIMENTATION : POURQUOI LA PRÉPARATION DES PRODUITS TRADITIONNELS MÉRITE AUSSI LE DÉBAT","Un nutrithérapeute interrogé par l’APS plaide pour des modes de préparation préservant davantage les micronutriments.","La nutrition rejoint les enjeux de prévention et d’éducation alimentaire.","<p>Dans un entretien accordé à l’APS, le nutrithérapeute Kéba Tamba recommande de mieux préserver les micronutriments des aliments, notamment en donnant davantage de place aux fruits, légumes et modes de préparation moins agressifs.</p><p>Ces recommandations relèvent d’un avis professionnel et ne remplacent pas les conseils médicaux. Elles ont néanmoins le mérite de remettre l’éducation nutritionnelle au centre du débat sur la prévention.</p>","APS","https://aps.sn/un-nutritherapeute-insiste-sur-la-necessite-dameliorer-la-preparation-des-aliments-dits-traditionnels/"],
["Économie","SÉNÉGAL–FMI : L’ACCORD TECHNIQUE OUVRE UNE NOUVELLE PHASE, MAIS N’EST PAS ENCORE L’APPROBATION FINALE","L’accord au niveau des services porte sur environ 2,2 milliards de dollars sur 36 mois.","La prochaine étape institutionnelle reste déterminante avant la mise en œuvre formelle du programme.","<p>Le Sénégal et les services du FMI sont parvenus à un accord au niveau des services sur un programme de 36 mois au titre de la Facilité élargie de crédit, pour environ 2,2 milliards de dollars.</p><p>La RTS et le FMI rappellent que cet accord doit encore franchir les procédures d’approbation de l’institution. Cette nuance est essentielle : il s’agit d’une étape majeure, mais pas encore de l’approbation définitive des financements.</p>","RTS / FMI","https://www.rts.sn/actualite/detail/a-la-une/senegal-fmi-un-accord-de-principe-sur-un-programme-de-financement-de-22-milliards-de-dollars-sur-36-mois"],
["Religion","DIAMAL-SANTHIE EN DEUIL APRÈS LE DÉCÈS DE SON KHALIFE","Serigne Cheikh Ahmadou Tidiane Cissé, dit Baye Cheikh Tidiane Raby, est décédé à 64 ans à Dakar après un accident de la circulation.","La communauté religieuse de Diamal-Santhie a accompagné son khalife à sa dernière demeure.","<p>La communauté religieuse de Diamal-Santhie, dans le département de Birkilane, est en deuil après le décès de son khalife Serigne Cheikh Ahmadou Tidiane Cissé, dit Baye Cheikh Tidiane Raby. Selon l’APS, il est décédé à l’âge de 64 ans à l’hôpital Idrissa Pouye de Grand-Yoff à la suite d’un accident de la circulation.</p><p>Le chef de l’État a présenté ses condoléances à la famille, à la communauté de Diamal-Santhie et aux fidèles.</p>","APS / Présidence","https://aps.sn/diamal-santhie-plonge-dans-le-deuil-apres-le-deces-de-son-khalife/"],
["Magal","APRÈS LE GRAND MAGAL, LE KHIDMA CONTINUE DANS LES RUES DE TOUBA","L’opération Set Setal des Baye Fall prolonge la mobilisation communautaire après le grand rassemblement.","Nettoyer la ville après l’affluence devient une séquence à part entière du service à Touba.","<p>Les Baye Fall ont lancé une vaste opération de Set Setal à Touba après le Grand Magal. L’appel relayé par l’APS invite les disciples de Serigne Touba et plus largement les musulmans à participer au nettoiement de la ville sainte.</p><p>Cette mobilisation rappelle que la gestion d’un événement de cette ampleur ne s’arrête pas au départ des pèlerins. Déchets, espaces publics et remise en état de la ville font pleinement partie de l’après-Magal.</p>","APS","https://aps.sn/touba-les-baye-fall-lancent-une-operation-de-set-setal-apres-le-magal/"],
["Afrique","ANTIDOPAGE : DAKAR PRÉPARE DÉJÀ L’AFRIQUE AU NOUVEAU CODE MONDIAL DE 2027","Les organisations antidopage des zones 2 et 3 d’Afrique sont réunies à Dakar jusqu’au 6 septembre.","La coopération régionale doit aider les pays à harmoniser leurs règles et renforcer la prévention.","<p>Dakar accueille la 19e réunion du Conseil de l’Organisation régionale antidopage des zones 2 et 3 d’Afrique. Les travaux portent notamment sur l’entrée en vigueur du nouveau Code mondial antidopage prévue le 1er janvier 2027.</p><p>Les responsables réunis veulent harmoniser les pratiques, renforcer les capacités techniques et juridiques et intensifier l’éducation des sportifs.</p>","APS / ONADS","https://aps.sn/pres-de-80-des-jeunes-devant-participer-aux-joj-dakar-2026-sensibilises-au-dopage-responsable/"],
["International","MIGRATION : LE RAPATRIEMENT VOLONTAIRE DE SÉNÉGALAIS DEPUIS LE MAROC SE POURSUIT","Un premier groupe de 120 Sénégalais devait quitter le Maroc par voie terrestre le 4 septembre.","L’opération concerne des migrants secourus ou interceptés en mer par la Marine royale marocaine.","<p>Selon la RTS, citant l’APS et une source diplomatique, un groupe de 120 Sénégalais devait quitter le Maroc le 4 septembre pour regagner le pays par voie terrestre via la Mauritanie.</p><p>Les autorités consulaires poursuivent leur coordination avec les autorités sénégalaises et marocaines pour organiser le retour volontaire d’autres ressortissants encore hébergés dans des centres d’accueil.</p>","RTS / APS","https://www.rts.sn/actualite/detail/a-la-une/maroc-120-senegalais-attendus-au-pays-dans-le-cadre-dun-rapatriement-volontaire"],
["Sport","SALY SARR ENTRE DANS L’HISTOIRE EN REMPORTANT LA DIAMOND LEAGUE À BRUXELLES","La triple sauteuse sénégalaise s’est imposée avec un bond de 14,96 m.","Une première historique pour l’athlétisme sénégalais sur la grande finale de la Diamond League.","<p>Saly Sarr a remporté vendredi la finale du triple saut féminin de la Diamond League à Bruxelles avec un bond de 14,96 m, selon l’APS. La championne d’Afrique devance les Cubaines Leyanis Pérez Hernández et Davisleydis Velazco.</p><p>Cette victoire intervient après son succès à Silesia le 23 août, où elle avait amélioré le record national. Elle confirme la progression de l’athlétisme sénégalais au plus haut niveau.</p>","APS","https://aps.sn/saly-sarr-remporte-la-grande-finale-de-la-diamond-league-a-bruxelles-une-premiere-pour-lathletisme-senegalais/"],
["Culture","CULTURES URBAINES : 570 MILLIONS FCFA MOBILISÉS POUR 244 PROJETS","Le Fonds de développement des cultures urbaines et des industries créatives finance cette année 244 projets et actions de mobilité.","L’enjeu affiché est de transformer davantage la création en activité économique durable.","<p>Le Fonds de développement des cultures urbaines et des industries créatives a mobilisé une enveloppe globale de 570 millions de francs CFA pour 244 projets artistiques et actions de mobilité, selon l’APS.</p><p>Sur 1 368 dossiers enregistrés, 855 dossiers complets issus des 14 régions ont été examinés. Les bénéficiaires doivent signer des conventions précisant les activités financées, le calendrier et les modalités de décaissement.</p>","APS / FDCUIC","https://aps.sn/une-enveloppe-de-570-millions-fcfa-mobilisee-pour-244-projets-culturels/"],
["Environnement","EAUX ÉPURÉES : L’ONAS VEUT SOUTENIR PRÈS DE 300 MARAÎCHERS","Un projet d’adduction d’eau épurée vise les producteurs des Grandes Niayes et de la Patte d’Oie.","La réutilisation des eaux usées traitées peut devenir un levier d’agriculture urbaine et d’économie circulaire.","<p>L’Office national de l’assainissement du Sénégal accélère son projet d’adduction d’eau épurée au profit des maraîchers des Grandes Niayes et de la Patte d’Oie. Selon l’APS, près de 300 producteurs sont concernés.</p><p>Le projet illustre une approche de valorisation des eaux usées traitées dans l’agriculture, avec un double enjeu : sécuriser une ressource pour les producteurs et mieux valoriser les infrastructures d’assainissement.</p>","APS / ONAS","https://aps.sn/eaux-epurees-lonas-accelere-la-valorisation-au-profit-de-pres-300-maraichers/"],
["Santé","DIPHTÉRIE : 34 CAS CONFIRMÉS ET SIX DÉCÈS, LE MINISTÈRE RENFORCE LA RIPOSTE","Les cas concernent huit districts sanitaires de six régions depuis la confirmation du premier cas le 1er août.","Kédougou concentre le plus grand nombre de cas confirmés, selon le ministère de la Santé.","<p>Le ministère de la Santé et de l’Hygiène publique a annoncé 34 cas confirmés de diphtérie, dont six décès, dans huit districts sanitaires relevant de six régions. Kédougou concentre 23 cas, devant Dakar avec cinq et Thiès avec trois.</p><p>Le ministère indique avoir renforcé les mesures de riposte avec les autorités territoriales et ses partenaires. Face à une maladie évitable par la vaccination, l’information officielle et le suivi des recommandations sanitaires restent essentiels.</p>","APS / Ministère de la Santé","https://aps.sn/diphterie-34-cas-confirmes-dans-six-regions-six-personnes-decedees-officiel/"],
["Éducation","RENTRÉE 2026 : APRÈS UN BAC À 54,5 %, LE DÉFI SE DÉPLACE VERS L’ORIENTATION ET L’ACCUEIL DES NOUVEAUX BACHELIERS","Le baccalauréat général 2026 compte 93 809 admis et 12 162 mentions, selon le ministère de l’Éducation.","Les résultats progressent, mais la prochaine étape concerne l’orientation et les capacités d’accueil du supérieur.","<p>Le taux national de réussite au baccalauréat général 2026 s’établit à 54,5 %, avec 93 809 admis et 12 162 mentions, selon les chiffres du ministère de l’Éducation relayés par la RTS.</p><p>Cette progression ouvre immédiatement un autre chantier : l’orientation des nouveaux bacheliers, l’information des familles et la capacité des établissements d’enseignement supérieur à accueillir les étudiants dans de bonnes conditions.</p>","RTS / Ministère de l’Éducation","https://www.rts.sn/actualite/detail/a-la-une/bac-2026-93-809-admis-12-162-mentions-et-un-taux-de-reussite-de-545"],
["Diaspora","MAROC : LE RETOUR VOLONTAIRE DE 120 SÉNÉGALAIS REMET L’ACCOMPAGNEMENT DES MIGRANTS AU PREMIER PLAN","Le convoi devait rejoindre le Sénégal par voie terrestre via la Mauritanie.","Au-delà du retour, la question de l’accueil et de la réinsertion des ressortissants demeure centrale.","<p>Un premier groupe de 120 Sénégalais devait quitter le Maroc le 4 septembre dans le cadre d’un rapatriement volontaire, selon la RTS et l’APS. Le convoi doit passer par la Mauritanie avant d’atteindre Rosso.</p><p>Pour la diaspora, cette opération rappelle l’importance du dispositif consulaire, mais aussi de l’accompagnement au retour : accueil, information, soutien psychosocial et possibilités de réinsertion économique.</p>","RTS / APS","https://www.rts.sn/actualite/detail/a-la-une/maroc-120-senegalais-attendus-au-pays-dans-le-cadre-dun-rapatriement-volontaire"],
["Technologies","NUMÉRIQUE : SENUM VEUT RAPPROCHER DAVANTAGE L’ADMINISTRATION DES TERRITOIRES","À Louga, Sénégal Numérique poursuit sa tournée consacrée à la modernisation des services publics.","Continuité, sécurité et résilience des infrastructures numériques sont au cœur des échanges.","<p>Sénégal Numérique a poursuivi à Louga sa tournée régionale autour de la transformation numérique de l’administration. Selon la RTS, les discussions ont porté sur l’efficacité des services publics, la coordination territoriale et la proximité avec les citoyens.</p><p>La visite des points de présence a également permis d’aborder la continuité des services, la sécurité des infrastructures et leur résilience face aux risques.</p>","RTS / SENUM","https://www.rts.sn/actualite/detail/a-la-une/a-louga-senum-veut-accelerer-la-transformation-numerique-des-territoires"]
] as const;
export async function GET(){
 const all=await adminListAll(); for(const x of all) if(x.alaUne) await adminUpdate(x.id,{alaUne:false});
 const made=[];
 for(const [categorie,titre,sousTitre,extrait,body,source,url] of A){
  const exists=(await adminListAll()).find(x=>x.titre===titre);
  if(exists){if(categorie==="Touba"&&!exists.alaUne)await adminUpdate(exists.id,{alaUne:true,epingle:true});made.push(exists);continue;}
  const a=await adminCreate({titre,sousTitre,extrait,categorie,genre:categorie==="Politique"||categorie==="Économie"||categorie==="Diaspora"?"Analyse":"Actualité",statut:"publie",auteur:"Rédaction Touba Infos",date:D,tempsLecture:"3 min",imageEmoji:"📰",imageGradient:"from-emerald-950 via-green-800 to-green-900",credit:`Source éditoriale : ${source}`,legende:titre,alaUne:categorie==="Touba",breaking:false,epingle:categorie==="Touba",vues:0,tags:[categorie,"5 septembre 2026"],contenu:body+S(source,url)}); made.push(a);
 }
 revalidatePath("/touba-infos"); revalidatePath("/touba-infos/fil-info"); revalidatePath("/");
 return NextResponse.json({ok:true,count:made.length,une:made.find(x=>x.alaUne)?.slug,articles:made.map(x=>({id:x.id,slug:x.slug,categorie:x.categorie}))});
}